### ISSUE TITLE
Q&A 12.11.2024

### ISSUE THREAD

**Issue by rosinusserrano** [rosinusserrano/pml_vqvae#1]
Collection of questions regarding the first milestone.

**Comment by rosinusserrano** [comment]
If VQVAE outputs discrete codes, how is it still variational?

**Comment by timonpalm** [comment]
Should we showcase our implementation on either images or audios, or both? I assume we can choose. Prefer images

**Comment by timonpalm** [comment]
What do they mean with this question?

`What kind of answers could be provided by machine learning algorithms about the data. What are
typical queries a human would ask?

Are the dataset overview questions meant in general for the dataset, or are they specific to our paper?

**Comment by rosinusserrano** [comment]
Why is CIFAR 8x8x10 and imagenet 32x32? Should it not be 8x8x1 but the number can take 10 values?

**Comment by rosinusserrano** [comment]
do we have to code pixelcnn and/or other methods like vimco theyve compared vqvae to?

**Comment by rosinusserrano** [comment]
Should we rather extend our project to audio or other modalities once finished with the imagenet or should we rather go deep and see what has been developed further in this area

**Comment by rosinusserrano** [comment]
What exactly is meant with modle prototype, the vqvae as abstract function class or so or a simpler baseline method?

**Comment by rosinusserrano** [comment]
Is crop+resize feature extraction and/or normalization? Is there Feature Extraction for us or do we not basically throw everything in?

**Comment by KonstantinAusborn** [comment]
Should we 

- evaluate Baseline performance in literature
- implement a Baseline and evaluate its performance

**Comment by rosinusserrano** [comment]
Are the dataset overview questions meant in general for the dataset, or are they specific to our paper?

**Comment by rosinusserrano** [comment]
What exactly is the posterior collapse and how do you note if it happens based on the generated images/videos?

**Comment by KonstantinAusborn** [comment]
We argue a basic Autoencoder is a good baseline for efficient Encoding and Image Generation, since it is simple enough to be implemented by us but fulfills the same task.
What is our coordinators opinion of that? Do we also need a non-NN Baseline or multiple Baselines, especially for efficient Encoding?

**Comment by rosinusserrano** [comment]
Paper specific questions (MIT DAVOR GEDANKEN MACHEN!):
- what is posterior collapse? how does it show?
- why are discrete distributions "flexible"?
- what does it mean to make effective use of the latent space? why can it model important features that usually span many dimensions in data space?

**Comment by rosinusserrano** [comment]
should we code pixelcnn and vimco and vae etc ourselves os ir it okay to take other git repos for that?

**Comment by rosinusserrano** [comment]
What is meant with
> Are there significant differences between the categories w.r.t. how well they can be characterized?

should we check the paper and look at images class for which it looks better than the others or should this information be read offf from the paper?

and 
> Can something non-technical be said about what the good features are?

Are "features" here the learnt representations / code embeddings? Or is feature here used like attribute/characteristic. Fundamentally different things but both kind of makes sense to me

**Comment by KonstantinAusborn** [comment]
> Should we
> 
>     * evaluate Baseline performance in literature
> 
>     * implement a Baseline and evaluate its performance

Evaluate our own

**Comment by KonstantinAusborn** [comment]
> Why is CIFAR 8x8x10 and imagenet 32x32? Should it not be 8x8x1 but the number can take 10 values?

The way we thought. Im notfall Codebase checken

**Comment by KonstantinAusborn** [comment]
> Is crop+resize feature extraction and/or normalization? Is there Feature Extraction for us or do we not basically throw everything in?

Talk about older things prior to deep learning, how did deep learning make this easier - Lit Review

**Comment by KonstantinAusborn** [comment]
> Paper specific questions (MIT DAVOR GEDANKEN MACHEN!):
> 
>     * what is posterior collapse? how does it show?
> 
>     * why are discrete distributions "flexible"?
> 
>     * what does it mean to make effective use of the latent space? why can it model important features that usually span many dimensions in data space?

- Closer to the Nature of an Image
- They are just saying its nice, just paper things

**Comment by KonstantinAusborn** [comment]
> should we code pixelcnn and vimco and vae etc ourselves os ir it okay to take other git repos for that?

Yes, but only in the next Milestone.

**Comment by KonstantinAusborn** [comment]
> Should we showcase our implementation on either images or audios, or both? I assume we can choose. Prefer images

Milestone 3 either deeper into Images, or go wider into different Modalities (Audio, Video etc.)

**Comment by KonstantinAusborn** [comment]
> What do they mean with this question?
> 
> `What kind of answers could be provided by machine learning algorithms about the data. What are typical queries a human would ask?
> 
> Are the dataset overview questions meant in general for the dataset, or are they specific to our paper?

Literature review about the diff. datasets
